import { useState, useEffect } from "react";
import Head from "next/head";
import Navbar from "../components/Navbar";
import "tailwindcss/tailwind.css";
import Map from "../components/Map";
import axios from "axios";
import List from "../components/List";

export default function Home() {
  const [coords, setCoords] = useState({ lat: 6.5239143, lng: 3.3312424 });
  const [childClicked, setChildClicked] = useState(null);
  const [parishes, setParishes] = useState([]);
  useEffect(() => {
    axios.get("/api").then((res) => {
      setParishes(res.data.parishes);
    });
  }, []);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen h-screen flex flex-col">
        <Navbar />
        <div className="flex flex-1 flex-col md:flex-row overflow-hidden">
          <List
            childClicked={childClicked}
            setChildClicked={setChildClicked}
            parishes={parishes}
            setCoords={setCoords}
          />
          <div className="flex-2 bg-gray-500 h-full w-full">
            <Map
              coords={coords}
              parishes={parishes}
              setChildClicked={setChildClicked}
            />
          </div>
        </div>
      </main>
    </div>
  );
}
