import { useState, useEffect } from "react";
import Head from "next/head";
import Navbar from "../components/Navbar";
import "tailwindcss/tailwind.css";
import Map from "../components/Map";
import axios from "axios";
import List from "../components/List";

export default function Home() {
  const [coords, setCoords] = useState({ lat: 6.54881, lng: 3.38683 });
  const [childClicked, setChildClicked] = useState("0");
  const [parishes, setParishes] = useState([]);
  const [searchedParishes, setSearchedParishes] = useState([]);
  const [search, setSearch] = useState("");
  useEffect(() => {
    axios.get("/api").then((res) => {
      setParishes(res.data.parishes);
    });
  }, []);

  useEffect(() => {
    if (search) {
      const regexp = new RegExp(search, "i");
      setSearchedParishes(parishes.filter((x) => regexp.test(x.name)));
    }
  }, [search]);

  return (
    <div>
      <Head>
        <title>RCCG Lagos Province 8</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen h-screen flex flex-col">
        <Navbar setSearch={setSearch} search={search} />
        <div className="flex flex-1 flex-col md:flex-row overflow-hidden">
          <List
            childClicked={childClicked}
            setChildClicked={setChildClicked}
            parishes={search ? searchedParishes : parishes}
            setCoords={setCoords}
          />
          <div className="flex-1 md:flex-2 bg-gray-500 h-full w-full">
            <Map
              coords={coords}
              parishes={search ? searchedParishes : parishes}
              setChildClicked={setChildClicked}
              childClicked={childClicked}
            />
          </div>
        </div>
      </main>
    </div>
  );
}
